module.exports = {
    ACTION_TOKEN: 'ActionToken',
    ACTION: 'Action',
    CART: 'Cart',
    CART_STATUS: 'CartStatus',
    COMMENT: 'Comment',
    COMMENT_STATUS: 'CommentStatus',
    GENDER: 'Gender',
    HISTORY_ACTION: 'HistoryAction',
    OAUTH_TOKEN: 'OAuthToken',
    PRODUCT: 'Product',
    PRODUCT_TYPE: 'ProductType',
    PRODUCT_SIZE: 'ProductSize',
    PRODUCT_STATUS: 'ProductStatus',
    PRODUCT_SECTION: 'ProductSection',
    PURCHASE: 'Purchase',
    PURCHASE_STATUS: 'PurchaseStatus',
    REPLY_COMMENT: 'ReplyComment',
    USER: 'User',
    USER_ROLE: 'UserRole',
    USER_STATUS: 'UserStatus',
    PRODUCT_RATING: 'ProductRating'
};
