module.exports = {
    ADMIN_REGISTER: 0,
    // ADMIN_DELETE: 1,
    // ADMIN_UPDATE: 2,
    USER_REGISTER: 3,
    USER_DELETE: 4,
    USER_UPDATE: 5,
    PRODUCT_CREATE: 6,
    PRODUCT_DELETE: 7,
    PRODUCT_UPDATE: 8
}
