module.exports = {
    ADMIN_REGISTER: 0,
    // ADMIN_DELETE: 1,
    // ADMIN_UPDATE: 2,
    SELLER_REGISTER: 3,
    // SELLER_DELETE: 4,
    // SELLER_UPDATE: 5,
    USER_REGISTER: 6,
    USER_DELETE: 7,
    USER_UPDATE: 8,
    PRODUCT_CREATE: 9,
    PRODUCT_DELETE: 10,
    PRODUCT_UPDATE: 11
}

//todo ADMIN_DELETE: 1, // ADMIN_UPDATE: 2,
//     // SELLER_DELETE: 4,
//     // SELLER_UPDATE: 5,
