module.exports = {
    ADMIN_REGISTER: 0,
    // ADMIN_DELETE: 1,
    // ADMIN_UPDATE: 2,
    SELLER_REGISTER: 3,
    // SELLER_DELETE: 4,
    // SELLER_UPDATE: 5,
    USER_REGISTER: 6,
    USER_DELETE: 7,
    USER_UPDATE: 8,
    PASSWORD_UPDATE: 9,
    CREATE_PRODUCT: 10,
    DELETE_PRODUCT: 11,
    UPDATE_PRODUCT: 12
}

//todo ADMIN_DELETE: 1, // ADMIN_UPDATE: 2,
//     // SELLER_DELETE: 4,
//     // SELLER_UPDATE: 5,
