module.exports = {
    blockUserHistory: 'blockUser',
    changePasswordHistory: 'changePassword',
    addProductToCartHistory: 'addProductToCart',
    createProductHistory: 'createProduct',
    createProductSectionHistory: 'createProductSection',
    createProductTypeHistory: 'createProductType',
    createUserHistory: 'createUser',
    deleteUserCartHistory: 'deleteUserCart',
    deleteCartProductHistory: 'deleteCartProduct',
    deleteProductHistory: 'deleteProduct',
    deleteProductSectionHistory: 'deleteProductSection',
    deleteProductTypeHistory: 'deleteProductType',
    getAllProductTypesHistory: 'getAllProductTypes',
    getAllProductSectionsHistory: 'getAllProductSections',
    getAllUsersHistory: 'getAllUsers',
    getUserByIdHistory: 'getUserById',
    deleteUserHistory: 'deleteUser',
    logoutUserHistory: 'logoutUser',
    refreshTokenHistory: 'refreshToken',
    registerUserHistory: 'registerUser',
    unlockUserHistory: 'unlockUser',
    updateProductHistory: 'updateProduct',
    updateProductInCartHistory: 'updateProductInCart',
    updateProductSectionHistory: 'updateProductSection',
    updateProductTypeHistory: 'updateProductType',
    updateUserHistory: 'updateUser',
};
