module.exports = {
    blockUserHistory: 'blockUser',
    changePasswordHistory: 'changePassword',
    createProductHistory: 'createProduct',
    createProductSectionHistory: 'createProductSection',
    createProductTypeHistory: 'createProductType',
    createUserHistory: 'createUser',
    deleteProductHistory: 'deleteProduct',
    deleteProductSectionHistory: 'deleteProductSection',
    deleteProductTypeHistory: 'deleteProductType',
    getAllProductTypesHistory: 'getAllProductTypes',
    getAllProductSectionsHistory: 'getAllProductSections',
    getAllUsersHistory: 'getAllUsers',
    getUserByIdHistory: 'getUserById',
    deleteUserHistory: 'deleteUser',
    getAllProductsHistory: 'getAllProducts',
    logoutUserHistory: 'logoutUser',
    refreshTokenHistory: 'refreshToken',
    registerUserHistory: 'registerUser',
    unblockUserHistory: 'unblockUser',
    updateProductHistory: 'updateProduct',
    updateProductSectionHistory: 'updateProductSection',
    updateProductTypeHistory: 'updateProductType',
    updateUserHistory: 'updateUser',
};
